openapi: 3.0.0
info:
  title: sampleapi
  description: 開発のサンプルです
  version: 1.0.0
paths:
  /articles:
    get:
      summary: Get all article
      operationId: getArticles
      description: Returns an array of articles
      responses:
        '200':
          description: ''
          content:
            application/json; charset=utf-8:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    result:
                      type: string
                    id:
                      type: integer
                    content:
                      type: string
                    createdAt:
                      type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                  message:
                    type: string
